[package]
name = "hosting_company"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version="0.6.18", features=["macros", "headers"]}
html-to-string-macro = "0.2.5"
tokio = {version="1.29", features=["rt-multi-thread", "macros"]}
